services:
  gungame:
    build:
      context: .
      dockerfile: Dockerfile
    image: gungame
    container_name: gungame
    environment:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - "${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR}"
    devices:
      - /dev/dri:/dev/dri
    stdin_open: true
    tty: true
    network_mode: host
    restart: "no"
